export const SET_PROJECT = "SET_PROJECT";
export const SET_TASKS = "SET_TASK";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_STATUS_TASK = "UPDATE_STATUS_TASK";
export const SET_LOADING_TASK = "SET_LOADING_TASK";
export const SET_LOADING_PROJECT = "SET_LOADING_PROJECT";
